[package]
name = "xtask"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.5.56", features = [
  "derive",
  "string",
  "env",
  "wrap_help",
] }
codegen = { path = "../codegen" }
heck = "0.5"
openapiv3 = "2.0"
quote = "1.0"
serde_json = "1.0"
