name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  validate:
    name: Validate Release
    runs-on: ubuntu-latest
    if: '!github.event.release.prerelease'
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
        with:
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy --package sumup -- --deny warnings

      - name: Build
        run: cargo build --package sumup --locked

      - name: Test
        run: cargo test --package sumup --locked

      - name: Package for publication
        run: cargo package --package sumup --list

  publish:
    name: Publish to crates.io
    needs: validate
    runs-on: ubuntu-latest
    if: '!github.event.release.prerelease'
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2

      - name: Login to crates.io
        run: cargo login "$CRATES_IO_TOKEN"
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

      - name: Publish to crates.io
        run: cargo publish --package sumup --locked
